services:
  phonebook-backend:
    image: phonebook-backend
    build:
      context: ./phonebook-backend/
      dockerfile: Dockerfile
    volumes:
      - ./phonebook-backend/:/app
    environment:
      - MONGODB_URI=mongodb+srv://fullstack:nNuuu7MpEqoaVsUK@cluster0.zxtcifc.mongodb.net/?retryWrites=true&w=majority
      - PORT=3001
    container_name: phonebook-backend
  
  phonebook-frontend:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend/
      dockerfile: Dockerfile
    volumes:
      - ./phonebook-frontend/:/app
    container_name: phonebook-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 18188:80
    container_name: phonebook-reverse-proxy
    depends_on:
      - phonebook-frontend # wait for the frontend container to be started
